version: '3.7'
services:
    db:
      image: mysql
      command: ["--default-authentication-plugin=mysql_native_password"]
      ports:
          - "3306:3306"
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony

    php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      ports:
        - "9000:9001"
      volumes:
        - app-sync:/usr/src/app
      links:
        - db
      extra_hosts:
        - "docker-host.localhost:127.0.0.1"

    nginx:
      image: nginx:1.15.3-alpine
      restart: on-failure
      volumes:
        - ./apps/my-symfony-app/public:/usr/src/app
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      ports:
        - 80:80
      depends_on:
        - php

    elk:
      image: willdurand/elk
      ports:
          - "81:80"
      volumes:
        - ./elk/logstash:/etc/logstash:cached
        - ./elk/logstash/patterns:/opt/logstash/patterns:cached
        - ./logs/symfony:/var/www/symfony/var/log:cached
        - ./logs/nginx:/var/log/nginx:cached

    adminer:
      image: adminer
      restart: on-failure
      ports:
        - 8080:8080
      links:
        - db

volumes:
  app-sync:
    external: true
